# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5003a00ba36fe84d483522cc58fa9aba2a8224cf0c6a6cf2d3773a025486c85fa0be6314c6f1c30939607053abf43e21b2eeef5608e5bfc0cd87763ada1bcc4a

test:
  secret_key_base: 93a27e79d24ed1d7e38fcdecc691208d7114bf72462068752b1293c83910a5e8acd2a24302973cdf89786d8bac54f694abc97e518208d96b47c5de270f007e58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
